import { assetUrl, cn } from "@/lib/utils";
import abilityIcons from "@/data/ability-icons.json";
import abilityNames from "@/data/ability-names.json";

// ability_name (as the ImportantAbilityUsed feed reports it, e.g.
// "citadel_ability_zip_line" or an item-active "upgrade_*") -> optimized WebP
// under /hud/abilities/ or /upgrades/. Generated by scripts/build-ability-icons.ts.
const ABILITY_ICON_MANIFEST = abilityIcons as Record<string, string>;
const ABILITY_NAME_MANIFEST = abilityNames as Record<string, string>;

export function abilityIconUrl(name: string): string | null {
  const url = name ? ABILITY_ICON_MANIFEST[name] : undefined;
  return url ? assetUrl(url) : null;
}

// Prefer Valve's in-game English localization. The formatter remains a fallback
// for identifiers absent from the current manifest (for example, an older demo).
export function prettifyAbilityName(name: string): string {
  const localized = ABILITY_NAME_MANIFEST[name];
  if (localized) return localized;

  return name
    .replace(/^citadel_ability_/, "")
    .replace(/^ability_/, "")
    .replace(/^citadel_/, "")
    .split("_")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// Small inline icon for the ability feed.
//
// These source images (m_strAbilityImage) are monochrome alpha-mask glyphs: the
// shape lives in the alpha channel and the RGB is a flat fill the game tints at
// render time. Most are authored white, but a handful (Dynamo's Stomp, Bebop's
// Uppercut, …) are authored *black* — so drawing the raw image makes those show
// up as black silhouettes. We instead paint the alpha shape ourselves via a CSS
// mask, so every glyph reads as the same colour regardless of its source RGB.
//
// Falls back to a muted square when the ability has no mapped image, so a feed
// row never shows a broken-image glyph.
export function AbilityIcon({
  name,
  size = 18,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const url = abilityIconUrl(name);
  if (!url) {
    return (
      <span
        style={{ width: size, height: size }}
        className={cn("flex-shrink-0 rounded bg-muted/60", className)}
      />
    );
  }
  const mask = `url("${url}") center / contain no-repeat`;
  return (
    <span
      aria-hidden
      style={{
        width: size,
        height: size,
        backgroundColor: "#fff",
        WebkitMask: mask,
        mask,
      }}
      className={cn("flex-shrink-0", className)}
    />
  );
}
