import * as React from "react";
import { ChevronDown, ChevronLeft } from "lucide-react";

import { AbilityIcon, prettifyAbilityName } from "@/components/ability-icon";
import { ItemIcon, itemDisplayName } from "@/components/item-icon";
import { RankBadge } from "@/components/rank-badge";
import type {
  AbilitySlot,
  ModifierSpan,
  PlayerPosition,
} from "@/components/map-view";
import {
  heroPortraitUrl,
  TEAM_COLORS,
  TEAM_NAMES,
  type HeroItems,
  type PlayerInfo,
} from "@/components/player-roster";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import itemStats from "@/data/item-stats.json";

type ItemCategory = "weapon" | "vitality" | "spirit";

// item ability name -> { category, soul cost }, generated by
// scripts/build-item-stats.ts from abilities.vdata.
const ITEM_STATS = itemStats as Record<
  string,
  { cat: ItemCategory; cost: number }
>;

// Deadlock's category accent colors: gun = orange, vitality = green,
// spirit = purple.
const CATEGORY_COLORS: Record<ItemCategory, string> = {
  weapon: "#df9b46",
  vitality: "#77b255",
  spirit: "#c27ce0",
};

// Souls as "X.Yk" (e.g. 6400 -> "6.4k"); 0 stays "0".
function formatSouls(value: number): string {
  if (value <= 0) return "0";
  return `${(value / 1000).toFixed(1)}k`;
}

type IconProps = { className?: string };

function HealthIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      className={className}
    >
      <path d="M57.7814 20.0248C55.2511 16.6262 51.9662 13.8614 48.1855 11.9483C44.4048 10.0351 40.2316 9.02587 35.9945 9C20.5247 9 8 22.2802 8 38.6586C8 68.2954 42.4102 87.6846 61.3834 116.752C62.8833 119.062 65.1167 119.062 66.6166 116.752C85.5898 87.6846 120 68.2954 120 38.6586C120 22.2364 107.475 9 92.0055 9C87.7684 9.02587 83.5952 10.0351 79.8145 11.9483C76.0338 13.8614 72.7489 16.6262 70.2186 20.0248C63.5183 28.7943 64.4817 28.7943 57.7814 20.0248Z" />
    </svg>
  );
}

function WeaponDamageIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      className={className}
    >
      <path d="M27.4815 24.52C27.4015 24.52 27.3215 24.52 27.2415 24.52C16.1015 24.52 6.96146 33.09 6.06146 44C5.98146 44.97 6.62146 45.77 7.39146 45.77H8.80146C10.3515 45.77 11.2015 48.91 10.6915 52.79L4.03146 103.36C3.77146 105.3 5.15146 106.87 7.11146 106.87H39.8715C41.8315 106.87 43.6215 105.3 43.8715 103.36L45.1615 93.53C45.6715 89.65 49.2615 86.51 53.1715 86.51H62.0015C73.7415 86.51 83.2515 76.99 83.2515 65.26L85.0215 59.06C86.0015 55.64 90.7615 52.86 95.6515 52.86H115.131C117.091 52.86 118.671 51.27 118.671 49.32V42.24H121.331C122.801 42.24 123.991 40.65 123.991 38.7V31.62C123.991 29.66 122.801 28.08 121.331 28.08H118.671V26.31C118.671 25.33 117.481 24.54 116.011 24.54H113.351L110.691 21H100.061L97.4015 24.54H34.5615C34.5615 24.54 32.7915 21 31.0215 21C29.2515 21 27.4815 24.54 27.4815 24.54V24.52ZM62.0115 77.65C55.1615 77.65 49.6115 72.1 49.6115 65.25C49.6115 58.4 55.1615 52.85 62.0115 52.85C68.8615 52.85 74.4115 58.4 74.4115 65.25C74.4115 72.1 68.8615 77.65 62.0115 77.65Z" />
    </svg>
  );
}

function SpiritIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      className={className}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M66.2532 6.37122C65.2804 4.54292 62.7195 4.54293 61.7471 6.37122L44.1015 39.5393C43.7322 40.233 43.0786 40.7202 42.3208 40.8656L6.09636 47.8197C4.0996 48.2031 3.30824 50.6996 4.70387 52.2131L30.0227 79.6659C30.5523 80.2401 30.8021 81.0281 30.7029 81.8119L25.9605 119.278C25.6991 121.343 27.7709 122.886 29.6061 121.993L62.8996 105.792C63.5958 105.453 64.4041 105.453 65.1007 105.792L98.3941 121.993C100.229 122.886 102.301 121.343 102.039 119.278L97.2971 81.8119C97.198 81.0281 97.4478 80.2401 97.9775 79.6659L123.296 52.2131C124.692 50.6996 123.9 48.2031 121.904 47.8197L85.6794 40.8656C84.9216 40.7202 84.2676 40.233 83.8987 39.5393L66.2532 6.37122ZM61.591 25.1546C62.4149 22.8569 65.585 22.8569 66.4088 25.1546L74.0468 46.4571C74.0262 46.6577 74.0427 46.8669 74.1027 47.0765L80.7174 70.2705C81.0437 71.4137 82.4267 71.8103 83.2841 71.0064L89.8403 64.8601C90.2444 64.4812 90.4268 63.9135 90.3212 63.3625L88.2169 52.3689H105.054C107.473 52.3689 108.549 55.4865 106.667 57.0454L88.2542 72.3055C88.002 72.3447 87.7539 72.4484 87.5329 72.6233L68.8712 87.3875C67.9513 88.1151 68.0948 89.5801 69.1376 90.1057L77.1093 94.1261C77.6011 94.3739 78.1829 94.3413 78.6453 94.0398L87.1338 88.5041L91.7117 104.982C92.3741 107.366 89.7479 109.28 87.7692 107.856L65.4784 91.817C65.1775 91.6009 64.8427 91.4579 64.4968 91.3885L49.094 80.6881C48.1185 80.0104 46.79 80.6347 46.6536 81.8342L45.6334 90.8129C45.5701 91.3705 45.7949 91.9218 46.2268 92.2674L53.6701 98.2257L40.3621 107.852C38.3884 109.28 35.7592 107.376 36.4112 104.992L43.1392 80.3897C43.1792 80.3161 43.2113 80.236 43.2337 80.1503L49.1451 57.6041C49.3367 56.8737 48.7365 56.1808 48.0061 56.2894L38.1921 57.7505C37.809 57.8078 37.4899 58.0808 37.3666 58.4569L34.247 67.9728L21.4828 57.6794C19.5888 56.152 20.607 53.0327 23.0163 52.9813L48.6012 52.4376C48.6776 52.4473 48.7558 52.4511 48.835 52.4491L69.3532 51.9036C70.4695 51.8738 71.1996 50.6927 70.7491 49.6451L67.0293 40.995C66.7781 40.411 66.2149 40.0346 65.5925 40.0346H56.256L61.591 25.1546Z"
      />
    </svg>
  );
}

function FireRateIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      className={className}
    >
      <path d="M78.6699 83C98.9999 83 103 91 103 91C103 91 98.9999 99 78.6699 99H51V83H78.6699ZM45.4199 88.5C46.5245 88.5 47.4199 89.3954 47.4199 90.5C47.4199 91.6046 46.5245 92.5 45.4199 92.5H13.4199C12.3154 92.5 11.4199 91.6046 11.4199 90.5C11.4199 89.3954 12.3154 88.5 13.4199 88.5H45.4199ZM98.6699 56C119 56 123 64 123 64C123 64 119 72 98.6699 72H71V56H98.6699ZM65 61.5C66.1046 61.5 67 62.3954 67 63.5C67 64.6046 66.1046 65.5 65 65.5H13C11.8954 65.5 11 64.6046 11 63.5C11 62.3954 11.8954 61.5 13 61.5H65ZM78.6699 29C98.9999 29 103 37 103 37C103 37 98.9999 45 78.6699 45H51V29H78.6699ZM45 35C46.1046 35 47 35.8954 47 37C47 38.1046 46.1046 39 45 39H13C11.8954 39 11 38.1046 11 37C11 35.8954 11.8954 35 13 35H45Z" />
    </svg>
  );
}

function CooldownIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      className={className}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M118.149 64C118.149 34.1257 93.8743 9.85143 64 9.85143C34.1257 9.85143 9.85143 34.1257 9.85143 64C9.85143 93.8743 34.1257 118.149 64 118.149C83.4514 118.149 100.594 107.84 110.126 92.2743C111.543 89.9657 114.583 89.2343 116.891 90.6514C119.2 92.0686 119.931 95.1086 118.514 97.4171C107.269 115.771 86.9943 128 64 128C28.6857 128 0 99.3143 0 64C0 28.6857 28.6857 0 64 0C99.3143 0 128 28.6857 128 64C128 66.72 125.806 68.9143 123.086 68.9143C120.366 68.9143 118.171 66.72 118.171 64H118.149Z"
      />
      <path d="M98.5596 92.8915L121.965 75.1772L125.691 104.389L98.5596 92.8915Z" />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M64.5484 97.3712C83.8855 97.3712 99.5655 81.6912 99.5655 62.3541C99.5655 43.0169 83.8855 27.3369 64.5484 27.3369C45.2112 27.3369 29.5312 43.0169 29.5312 62.3541C29.5312 81.6912 45.2112 97.3712 64.5484 97.3712ZM69.4627 40.4798C69.4627 37.7598 67.2684 35.5655 64.5484 35.5655C61.8284 35.5655 59.6341 37.7598 59.6341 40.4798V62.3541C59.6341 65.0741 61.8284 67.2683 64.5484 67.2683H86.4227C89.1427 67.2683 91.337 65.0741 91.337 62.3541C91.337 59.6341 89.1427 57.4398 86.4227 57.4398H69.4627V40.4798Z"
      />
    </svg>
  );
}

function AmmoIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      className={className}
    >
      <path d="M16 0C16 0 0 8 0 48.64V104H32V48.64C32 8 16 0 16 0Z" />
      <path d="M32 112H0V128H32V112Z" />
      <path d="M64 0C64 0 48 8 48 48.64V104H80V48.64C80 8 64 0 64 0Z" />
      <path d="M80 112H48V128H80V112Z" />
      <path d="M112 0C112 0 96 8 96 48.64V104H128V48.64C128 8 112 0 112 0Z" />
      <path d="M128 112H96V128H128V112Z" />
    </svg>
  );
}

const ITEM_PIXELS = 48;
const SLOT_COUNT = 10;
const ABILITY_PIXELS = 36;
// Abilities have three upgrade tiers; we render one segment per tier.
const ABILITY_TIERS = 3;
const TICKS_PER_SECOND = 64;

/** One reconstructed cooldown period for an ability, in absolute ticks. */
export type CooldownSpan = {
  /** Tick the cooldown started (the cast). */
  start: number;
  /** Tick the ability becomes available again. */
  end: number;
  /** Total cooldown length in seconds (the ring's full sweep). */
  total: number;
};

/** Charge count over time for a charge-based ability (valid from `startTick`). */
export type ChargeState = {
  startTick: number;
  /** Available charges at this point. */
  count: number;
  /** Tick the regenerating charge began filling (anchor for its bar). */
  rechargeStart: number;
  /** Tick the regenerating charge completes. */
  rechargeEnd: number;
  recharging: boolean;
};

/** Reconstructed cooldown + charge timeline for one ability. */
export type AbilityCooldown = {
  /** Max charges seen; ≥ 2 marks a charge-based ability (show pills, no ring). */
  maxCharges: number;
  cooldowns: CooldownSpan[];
  charges: ChargeState[];
};

// The cooldown active at `tick`, or null if the ability is ready. Spans are
// tick-ordered and non-overlapping, so the latest one starting at or before
// `tick` is the only candidate.
function activeCooldown(
  spans: CooldownSpan[] | undefined,
  tick: number,
): { remaining: number; total: number } | null {
  if (!spans) return null;
  for (let i = spans.length - 1; i >= 0; i--) {
    if (spans[i].start <= tick) {
      return tick < spans[i].end
        ? {
            remaining: (spans[i].end - tick) / TICKS_PER_SECOND,
            total: spans[i].total,
          }
        : null;
    }
  }
  return null;
}

// Charge count + recharge progress (0..1 for the regenerating charge) at `tick`.
function chargeAt(
  states: ChargeState[],
  tick: number,
  maxCharges: number,
): { count: number; recharging: boolean; progress: number } | null {
  for (let i = states.length - 1; i >= 0; i--) {
    const s = states[i];
    if (s.startTick <= tick) {
      const recharging =
        s.recharging && s.count < maxCharges && tick < s.rechargeEnd;
      const span = s.rechargeEnd - s.rechargeStart;
      const progress =
        recharging && span > 0
          ? Math.min(1, Math.max(0, (tick - s.rechargeStart) / span))
          : 0;
      return { count: s.count, recharging, progress };
    }
  }
  return null;
}

export function PlayerDetail({
  player,
  stats,
  items,
  abilities,
  abilityLevels,
  abilityCooldowns,
  modifiers,
  players,
  tick,
  regTick,
  onBack,
}: {
  player: PlayerInfo;
  stats: PlayerPosition | undefined;
  items: HeroItems | undefined;
  abilities: AbilitySlot[] | undefined;
  abilityLevels: Map<number, number> | undefined;
  /** Reconstructed cooldown + charge timeline per ability_id (active player). */
  abilityCooldowns?: Map<number, AbilityCooldown>;
  modifiers?: ModifierSpan[];
  players?: PlayerInfo[];
  tick?: number;
  /** Current non-paused match tick, used by modifier countdowns. */
  regTick?: number;
  onBack: () => void;
}) {
  const portrait = heroPortraitUrl(player.hero_id);
  const teamLabel = TEAM_NAMES[player.team] ?? `Team ${player.team}`;
  const teamColor = TEAM_COLORS[player.team] ?? "#888";

  // Pad to a fixed 10-slot inventory so empty slots stay visible.
  const slots = (items?.items ?? []).slice(0, SLOT_COUNT);
  while (slots.length < SLOT_COUNT) {
    slots.push({ ability_id: 0, ability_name: "" });
  }

  // Souls invested per category in the current inventory (sum of item costs).
  const investment = React.useMemo(() => {
    const t: Record<ItemCategory, number> = {
      weapon: 0,
      vitality: 0,
      spirit: 0,
    };
    for (const it of items?.items ?? []) {
      const stat = ITEM_STATS[it.ability_name];
      if (stat) t[stat.cat] += stat.cost;
    }
    return t;
  }, [items]);

  return (
    <div className="flex min-h-0 min-w-[20rem] flex-1 flex-col gap-3">
      <div className="flex flex-shrink-0 items-center gap-2">
        <button
          type="button"
          onClick={onBack}
          aria-label="Back to teams"
          className="flex size-7 flex-shrink-0 items-center justify-center rounded-md border border-border bg-card text-foreground transition-colors hover:bg-accent"
        >
          <ChevronLeft className="size-4" />
        </button>
        {portrait ? (
          <img
            src={portrait}
            alt={player.hero_name}
            width={32}
            height={32}
            className="size-8 flex-shrink-0 rounded object-contain"
          />
        ) : (
          <div className="size-8 flex-shrink-0 rounded bg-muted" />
        )}
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-semibold leading-tight">
            {player.hero_name || "—"}
          </p>
          <p className="truncate text-xs text-muted-foreground leading-tight">
            {player.name || "—"}
          </p>
        </div>
        <RankBadge rank={player.rank} className="size-8" />
        <span
          className="text-xs font-semibold uppercase tracking-wide"
          style={{ color: teamColor }}
        >
          {teamLabel}
        </span>
      </div>

      <div className="flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto pr-1">
        <CollapsibleSection
          title="Health"
          right={
            <span className="text-xs font-medium tabular-nums">
              <span className="text-foreground">{stats?.health ?? 0}</span>
              <span className="text-muted-foreground">
                {" / "}
                {stats?.max_health ?? 0}
              </span>
            </span>
          }
        >
          <HealthBar
            health={stats?.health ?? 0}
            maxHealth={stats?.max_health ?? 0}
          />
          <BarrierBar
            barrier={stats?.barrier ?? 0}
            maxHealth={stats?.max_health ?? 0}
          />
        </CollapsibleSection>

        {abilities && abilities.length > 0 && (
          <CollapsibleSection title="Abilities">
            <div className="flex gap-2">
              {abilities.map((a) => {
                const ac = abilityCooldowns?.get(a.ability_id);
                const isCharge = (ac?.maxCharges ?? 0) >= 2;
                const charge = isCharge
                  ? chargeAt(ac!.charges, tick ?? 0, ac!.maxCharges)
                  : null;
                // The ring shows the per-cast cooldown for all abilities —
                // including charge abilities (the between-cast lockout), where
                // it sits alongside the charge pills.
                const cd = activeCooldown(ac?.cooldowns, tick ?? 0);
                return (
                  <div
                    key={a.ability_id}
                    className="flex min-w-0 flex-1 flex-col items-center gap-1.5"
                  >
                    {/* Charge pills above the icon. The row is always present
                        (empty for non-charge abilities) so icons stay aligned. */}
                    <div className="flex h-1.5 w-full items-center justify-center gap-0.5">
                      {isCharge &&
                        Array.from({ length: ac!.maxCharges }, (_, i) => {
                          const full = charge ? i < charge.count : false;
                          const filling =
                            charge?.recharging && i === charge.count;
                          return (
                            <div
                              key={i}
                              className="h-full flex-1 overflow-hidden rounded-full bg-white/25"
                            >
                              {full ? (
                                <div className="h-full w-full bg-white" />
                              ) : filling ? (
                                <div
                                  className="h-full bg-white"
                                  style={{
                                    width: `${(charge?.progress ?? 0) * 100}%`,
                                  }}
                                />
                              ) : null}
                            </div>
                          );
                        })}
                    </div>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <div className="relative flex aspect-square w-full items-center justify-center rounded-md border border-border bg-muted/20">
                          <AbilityIcon
                            name={a.ability_name}
                            size={ABILITY_PIXELS}
                          />
                          {cd && (
                            <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
                              {/* Semi-transparent pie that empties clockwise as
                                  the cooldown elapses (the wedge = time left). */}
                              <div
                                className="absolute inset-0 rounded-full"
                                style={{
                                  background: `conic-gradient(rgb(0 0 0 / 0.55) 0deg ${
                                    (cd.remaining / cd.total) * 360
                                  }deg, transparent ${
                                    (cd.remaining / cd.total) * 360
                                  }deg 360deg)`,
                                }}
                              />
                              <span className="relative text-xs font-bold tabular-nums text-white [text-shadow:0_1px_2px_rgb(0_0_0/0.95)]">
                                {cd.remaining >= 10
                                  ? Math.round(cd.remaining)
                                  : cd.remaining.toFixed(1)}
                              </span>
                            </div>
                          )}
                        </div>
                      </TooltipTrigger>
                      <TooltipContent>
                        {prettifyAbilityName(a.ability_name)}
                        {cd && ` · ${cd.remaining.toFixed(1)}s`}
                        {charge && ` · ${charge.count}/${ac!.maxCharges} charges`}
                      </TooltipContent>
                    </Tooltip>
                    <LevelBars
                      level={abilityLevels?.get(a.ability_id) ?? 0}
                      color={teamColor}
                    />
                  </div>
                );
              })}
            </div>
          </CollapsibleSection>
        )}

        {modifiers && (
          <CollapsibleSection
            title="Modifiers"
            right={
              <span className="text-xs font-medium tabular-nums text-muted-foreground">
                {modifiers.length || ""}
              </span>
            }
          >
            <ModifierList
              modifiers={modifiers}
              selfTeam={player.team}
              selfHeroId={player.hero_id}
              players={players}
              regTick={regTick ?? 0}
            />
          </CollapsibleSection>
        )}

        <CollapsibleSection
          title="Items"
          right={
            <span className="flex items-center gap-2 text-xs font-semibold tabular-nums">
              <span
                style={{ color: CATEGORY_COLORS.weapon }}
                title={`Weapon: ${investment.weapon.toLocaleString()}`}
              >
                {formatSouls(investment.weapon)}
              </span>
              <span
                style={{ color: CATEGORY_COLORS.vitality }}
                title={`Vitality: ${investment.vitality.toLocaleString()}`}
              >
                {formatSouls(investment.vitality)}
              </span>
              <span
                style={{ color: CATEGORY_COLORS.spirit }}
                title={`Spirit: ${investment.spirit.toLocaleString()}`}
              >
                {formatSouls(investment.spirit)}
              </span>
            </span>
          }
        >
          <div className="grid grid-cols-5 gap-2">
            {slots.map((it, i) =>
              it.ability_id ? (
                (() => {
                  // Frame each item in its category color (gun/vitality/spirit);
                  // border-box keeps the 48px footprint aligned with empty slots.
                  const cat = ITEM_STATS[it.ability_name]?.cat;
                  const color = cat ? CATEGORY_COLORS[cat] : undefined;
                  return (
                    <ItemIcon
                      key={`${i}-${it.ability_id}`}
                      abilityId={it.ability_id}
                      abilityName={it.ability_name}
                      size={ITEM_PIXELS}
                      className={cn("border-2", !color && "border-border")}
                      style={color ? { borderColor: color } : undefined}
                    />
                  );
                })()
              ) : (
                <div
                  key={`empty-${i}`}
                  style={{ width: ITEM_PIXELS, height: ITEM_PIXELS }}
                  className="rounded border border-border bg-muted/30"
                />
              ),
            )}
          </div>
        </CollapsibleSection>

        <CollapsibleSection title="Bonuses">
          <dl className="grid grid-cols-3 gap-x-3 gap-y-2">
            <Bonus
              icon={HealthIcon}
              label="Bonus HP"
              value={stats?.bonus_health ?? 0}
            />
            <Bonus
              icon={WeaponDamageIcon}
              label="Weapon DMG"
              value={stats?.weapon_damage ?? 0}
              percent
            />
            <Bonus
              icon={SpiritIcon}
              label="Spirit"
              value={stats?.spirit_power ?? 0}
            />
            <Bonus
              icon={FireRateIcon}
              label="Fire Rate"
              value={stats?.fire_rate ?? 0}
              percent
            />
            <Bonus
              icon={CooldownIcon}
              label="CDR"
              value={stats?.cooldown_reduction ?? 0}
              percent
            />
            <Bonus
              icon={AmmoIcon}
              label="Ammo"
              value={stats?.ammo ?? 0}
              percent
            />
          </dl>
        </CollapsibleSection>
      </div>
    </div>
  );
}

// A bordered card whose body collapses when the header is clicked. `right` is
// optional trailing header content (e.g. the health value or item totals).
function CollapsibleSection({
  title,
  right,
  children,
}: {
  title: string;
  right?: React.ReactNode;
  children: React.ReactNode;
}) {
  const [open, setOpen] = React.useState(true);
  return (
    <section className="rounded-md border border-border bg-card p-3">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        className="flex w-full items-center justify-between gap-2 text-left"
      >
        <span className="flex items-center gap-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          <ChevronDown
            className={cn(
              "size-3.5 shrink-0 transition-transform",
              !open && "-rotate-90",
            )}
            aria-hidden
          />
          {title}
        </span>
        {right}
      </button>
      {open && <div className="mt-2">{children}</div>}
    </section>
  );
}

function HealthBar({
  health,
  maxHealth,
}: {
  health: number;
  maxHealth: number;
}) {
  const pct =
    maxHealth > 0
      ? Math.max(0, Math.min(1, health / maxHealth)) * 100
      : 0;
  // Hue shifts from green (full) to red (empty) — quick visual scan in
  // addition to the explicit numbers above.
  const hue = (pct / 100) * 120;
  const fill = pct > 0 ? `hsl(${hue} 70% 45%)` : "transparent";
  return (
    <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
      <div
        className="h-full rounded-full transition-all"
        style={{ width: `${pct}%`, backgroundColor: fill }}
      />
    </div>
  );
}

function BarrierBar({
  barrier,
  maxHealth,
}: {
  barrier: number;
  maxHealth: number;
}) {
  const remaining = Number.isFinite(barrier) ? Math.max(0, barrier) : 0;
  const pct =
    maxHealth > 0
      ? Math.max(0, Math.min(1, remaining / maxHealth)) * 100
      : 0;
  return (
    <div className="mt-1.5 space-y-1" title="Current barrier remaining">
      <div className="flex items-center justify-between text-[10px] font-medium uppercase tracking-wide text-cyan-200/80">
        <span>Barrier</span>
        <span className="tabular-nums">{Math.round(remaining)}</span>
      </div>
      <div className="h-1.5 w-full overflow-hidden rounded-full bg-cyan-950/60">
        <div
          className="h-full rounded-full bg-cyan-300 transition-all"
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

// Three horizontally-stacked segments, `level` of them filled, showing how many
// upgrade tiers are spent on an ability (0 = unlocked / no tiers, up to 3).
function LevelBars({ level, color }: { level: number; color: string }) {
  return (
    <div
      className="flex w-full gap-0.5"
      title={level > 0 ? `Tier ${Math.min(level, ABILITY_TIERS)}` : "Unlocked"}
    >
      {Array.from({ length: ABILITY_TIERS }, (_, i) => (
        <span
          key={i}
          className={cn(
            "h-1.5 flex-1 rounded-sm",
            i < level ? "" : "bg-muted",
          )}
          style={i < level ? { backgroundColor: color } : undefined}
        />
      ))}
    </div>
  );
}

function Bonus({
  icon: Icon,
  label,
  value,
  percent,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: number;
  percent?: boolean;
}) {
  return (
    <div>
      <dt className="flex items-center gap-1 text-[10px] uppercase tracking-wide text-muted-foreground">
        <Icon className="size-3" />
        {label}
      </dt>
      <dd className="text-sm font-medium tabular-nums">
        {formatBonus(value)}
        {percent ? "%" : ""}
      </dd>
    </div>
  );
}

function formatBonus(value: number): string {
  // Stat-modifier values are floats; small magnitudes round nicely with 1
  // decimal, larger values look better as integers.
  if (value === 0) return "0";
  const abs = Math.abs(value);
  const rounded =
    abs >= 100 ? Math.round(value) : Math.round(value * 10) / 10;
  return rounded > 0 ? `+${rounded}` : `${rounded}`;
}

// One displayed modifier, after collapsing the raw spans that share a source
// and caster into a single row.
type ModRow = {
  key: string;
  abilityId: number;
  abilityName: string;
  label: string;
  isItem: boolean;
  casterHeroId: number;
  /** Highest in-game stack count seen, and how many raw spans were grouped. */
  stacks: number;
  count: number;
  /** Seconds left at the current tick; null = indefinite. */
  remaining: number | null;
  /** True if applied by a hero on the other team (incoming debuff). */
  incoming: boolean;
};

// Reconstruct a readable label + icon hint from a span's source. Items are the
// `upgrade_*` family (great icon + localized-name coverage); everything else is
// a hero ability, with the modifier's own name as the last-resort label.
function modifierLabel(m: ModifierSpan): { label: string; isItem: boolean } {
  if (m.ability_name) {
    if (m.ability_name.startsWith("upgrade_")) {
      return { label: itemDisplayName(m.ability_name), isItem: true };
    }
    return { label: prettifyAbilityName(m.ability_name), isItem: false };
  }
  // Only the modifier's own name resolved — strip the modifier_ prefix and
  // reuse the ability prettifier for the rest.
  return {
    label: prettifyAbilityName(m.modifier_name.replace(/^modifier_/, "")),
    isItem: false,
  };
}

function ModifierList({
  modifiers,
  selfTeam,
  selfHeroId,
  players,
  regTick,
}: {
  modifiers: ModifierSpan[];
  selfTeam: number;
  selfHeroId: number;
  players?: PlayerInfo[];
  regTick: number;
}) {
  const heroById = React.useMemo(() => {
    const m = new Map<number, PlayerInfo>();
    for (const p of players ?? []) m.set(p.hero_id, p);
    return m;
  }, [players]);

  const rows = React.useMemo(() => {
    const groups = new Map<string, ModRow>();
    for (const m of modifiers) {
      const { label, isItem } = modifierLabel(m);
      if (!label) continue;
      const source = m.ability_id || `m:${m.modifier_name}`;
      const key = `${source}|${m.caster_hero_id}`;
      const remaining =
        m.duration > 0
          ? Math.max(
              0,
              m.duration -
                (regTick - m.applied_reg_tick) / TICKS_PER_SECOND,
            )
          : null;
      const casterTeam = heroById.get(m.caster_hero_id)?.team;
      const incoming =
        m.caster_hero_id !== 0 &&
        m.caster_hero_id !== selfHeroId &&
        casterTeam != null &&
        casterTeam !== selfTeam;
      const cur = groups.get(key);
      if (cur) {
        cur.count += 1;
        cur.stacks = Math.max(cur.stacks, m.stacks);
        // Indefinite (null) outranks any finite remaining.
        cur.remaining =
          cur.remaining == null || remaining == null
            ? null
            : Math.max(cur.remaining, remaining);
      } else {
        groups.set(key, {
          key,
          abilityId: m.ability_id,
          abilityName: m.ability_name,
          label,
          isItem,
          casterHeroId: m.caster_hero_id,
          stacks: m.stacks,
          count: 1,
          remaining,
          incoming,
        });
      }
    }
    // Incoming enemy debuffs first, then by remaining time (timed effects
    // before passives), then alphabetically for stability.
    return [...groups.values()].sort((a, b) => {
      if (a.incoming !== b.incoming) return a.incoming ? -1 : 1;
      const ar = a.remaining ?? Infinity;
      const br = b.remaining ?? Infinity;
      if (ar !== br) return ar - br;
      return a.label.localeCompare(b.label);
    });
  }, [modifiers, heroById, selfTeam, selfHeroId, regTick]);

  if (rows.length === 0) {
    return (
      <p className="text-xs text-muted-foreground">No active modifiers.</p>
    );
  }

  return (
    <ul className="flex flex-col gap-1.5">
      {rows.map((r) => {
        const caster =
          r.casterHeroId && r.casterHeroId !== selfHeroId
            ? heroById.get(r.casterHeroId)
            : undefined;
        const multiplier = r.stacks > 1 ? r.stacks : r.count > 1 ? r.count : 0;
        return (
          <li
            key={r.key}
            className={cn(
              "flex items-center gap-2 rounded-md border px-2 py-1.5",
              r.incoming
                ? "border-destructive/40 bg-destructive/5"
                : "border-border bg-muted/20",
            )}
          >
            <div className="flex size-7 flex-shrink-0 items-center justify-center">
              {r.isItem ? (
                <ItemIcon
                  abilityId={r.abilityId}
                  abilityName={r.abilityName}
                  size={26}
                  className="rounded"
                />
              ) : r.abilityName ? (
                <AbilityIcon name={r.abilityName} size={22} />
              ) : (
                <div className="size-5 rounded bg-muted/60" />
              )}
            </div>
            <div className="min-w-0 flex-1">
              <p className="truncate text-xs font-medium leading-tight">
                {r.label}
                {multiplier > 0 && (
                  <span className="ml-1 text-muted-foreground">
                    ×{multiplier}
                  </span>
                )}
              </p>
              {caster && (
                <p className="truncate text-[10px] leading-tight text-muted-foreground">
                  from {caster.hero_name || caster.name || "—"}
                </p>
              )}
            </div>
            {r.remaining != null && (
              <span className="flex-shrink-0 text-[10px] tabular-nums text-muted-foreground">
                {r.remaining < 0.1
                  ? "<0.1"
                  : r.remaining >= 10
                    ? Math.round(r.remaining)
                    : r.remaining.toFixed(1)}
                s
              </span>
            )}
          </li>
        );
      })}
    </ul>
  );
}
